#include "SpectralEngine.h"
void SpectralEngine::prepare(double sr,int channels){sampleRate=sr;fft=std::make_unique<juce::dsp::FFT>(order);window.resize(fftSize);for(int i=0;i<fftSize;++i)window[(size_t)i]=std::sqrt(0.5f-0.5f*std::cos(juce::MathConstants<float>::twoPi*i/(fftSize-1)));c.clear();c.resize((size_t)juce::jmax(1,channels));for(auto& s:c){s.history.assign(fftSize,0);s.ola.assign(ringSize,0);s.norm.assign(ringSize,0);s.fftData.assign(fftSize*2,0);s.magDb.assign(fftSize/2+1,-120);s.reduction.assign(fftSize/2+1,0);s.lastWet.assign(fftSize/2+1,0);s.det.prepare(fftSize/2+1,sr,fftSize);}reset();}
void SpectralEngine::reset(){for(auto& s:c){std::fill(s.history.begin(),s.history.end(),0);std::fill(s.ola.begin(),s.ola.end(),0);std::fill(s.norm.begin(),s.norm.end(),0);s.t=0;s.histPos=0;s.det.reset();s.trans.reset();}}
float SpectralEngine::processOne(Chan& s,float x){ long long t=s.t; int out=(int)(t%ringSize); float y=(t>=fullOverlapAt && s.norm[(size_t)out]>1e-7f)?s.ola[(size_t)out]/s.norm[(size_t)out]:0.0f; s.ola[(size_t)out]=0;s.norm[(size_t)out]=0; s.history[(size_t)s.histPos]=x;s.histPos=(s.histPos+1)%fftSize; float tf=s.trans.process(x,params.transient); ++s.t; if(s.t>=fftSize && (s.t%hop)==0)frame(s,tf); return y; }
void SpectralEngine::frame(Chan& s,float transientFactor){ for(int k=0;k<fftSize;++k){int idx=(s.histPos+k)%fftSize;s.fftData[(size_t)k]=s.history[(size_t)idx]*window[(size_t)k];} std::fill(s.fftData.begin()+fftSize,s.fftData.end(),0); fft->performRealOnlyForwardTransform(s.fftData.data());
 for(int i=0;i<=fftSize/2;++i){float re=s.fftData[(size_t)2*i],im=(i==0||i==fftSize/2)?0.0f:s.fftData[(size_t)2*i+1];s.magDb[(size_t)i]=juce::Decibels::gainToDecibels(std::sqrt(re*re+im*im)/(float)fftSize+1e-12f,-120.0f);} s.det.compute(s.magDb,s.reduction,params.depth,params.sharpness,params.selectivity,params.attackMs,params.releaseMs,params.lowHz,params.highHz,params.biasDb,params.curveDb,transientFactor);
 for(int i=0;i<=fftSize/2;++i){float g=juce::Decibels::decibelsToGain(s.reduction[(size_t)i]); if(params.delta)g=1.0f-g; s.fftData[(size_t)2*i]*=g; if(i>0&&i<fftSize/2)s.fftData[(size_t)2*i+1]*=g; }
 fft->performRealOnlyInverseTransform(s.fftData.data()); long long start=s.t; for(int k=0;k<fftSize;++k){int ri=(int)((start+k)%ringSize);float w=window[(size_t)k];s.ola[(size_t)ri]+=s.fftData[(size_t)k]*w;s.norm[(size_t)ri]+=w*w;} }
void SpectralEngine::process(juce::AudioBuffer<float>& b){int ch=juce::jmin((int)c.size(),b.getNumChannels()); if(ch==2&&params.mode==2){for(int i=0;i<b.getNumSamples();++i){float l=b.getSample(0,i),r=b.getSample(1,i),m=(l+r)*0.70710678f,s=(l-r)*0.70710678f;m=processOne(c[0],m);s=processOne(c[1],s);b.setSample(0,i,(m+s)*0.70710678f);b.setSample(1,i,(m-s)*0.70710678f);}} else {for(int cc=0;cc<ch;++cc)for(int i=0;i<b.getNumSamples();++i)b.setSample(cc,i,processOne(c[(size_t)cc],b.getSample(cc,i)));}}
std::vector<float> SpectralEngine::getLastSpectrum() const{return c.empty()?std::vector<float>{}:c[0].magDb;} std::vector<float> SpectralEngine::getLastReduction() const{return c.empty()?std::vector<float>{}:c[0].reduction;}
